config/routes.rb
Kimatakubot::Application.routes.draw do
  resources :tweets

  resources :releases

  resources :paydays

  resources :homes

  root 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/payday.rb
class Payday < ActiveRecord::Base
end

app/models/release.rb
class Release < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render action: 'show', status: :created, location: @home }
      else
        format.html { render action: 'new' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

app/controllers/paydays_controller.rb
class PaydaysController < ApplicationController
  before_action :set_payday, only: [:show, :edit, :update, :destroy]

  # GET /paydays
  # GET /paydays.json
  def index
    @paydays = Payday.order(payday: :asc).page(params[:page]).per(10)
  end

  # GET /paydays/1
  # GET /paydays/1.json
  def show
  end

  # GET /paydays/new
  def new
    @payday = Payday.new
  end

  # GET /paydays/1/edit
  def edit
  end

  # POST /paydays
  # POST /paydays.json
  def create
    @payday = Payday.new(payday_params)

    respond_to do |format|
      if @payday.save
        format.html { redirect_to @payday, notice: 'Payday was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payday }
      else
        format.html { render action: 'new' }
        format.json { render json: @payday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paydays/1
  # PATCH/PUT /paydays/1.json
  def update
    respond_to do |format|
      if @payday.update(payday_params)
        format.html { redirect_to @payday, notice: 'Payday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paydays/1
  # DELETE /paydays/1.json
  def destroy
    @payday.destroy
    respond_to do |format|
      format.html { redirect_to paydays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payday
      @payday = Payday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payday_params
      params.require(:payday).permit(:title, :twitter_acount_name, :payday)
    end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:show, :edit, :update, :destroy]

  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
  end

  # GET /releases/new
  def new
    @release = Release.new
  end

  # GET /releases/1/edit
  def edit
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(release_params)

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render action: 'show', status: :created, location: @release }
      else
        format.html { render action: 'new' }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /releases/1
  # PATCH/PUT /releases/1.json
  def update
    respond_to do |format|
      if @release.update(release_params)
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release.destroy
    respond_to do |format|
      format.html { redirect_to releases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_release
      @release = Release.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def release_params
      params.require(:release).permit(:title, :description, :release_at)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:title, :tweet, :twitter_acount_name, :started_at, :ended_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      renderer = Redcarpet::Render::HTML.new(:hard_wrap => true)
      @markdown = Redcarpet::Markdown.new(renderer)
    end
    @markdown.render(text).html_safe
  end
end

app/helpers/paydays_helper.rb
module PaydaysHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/homes/index.html.erb
<h1>kimatakubot</h1>

app/views/layouts/_twitter.html.erb
<div id="yo-button"></div>
<script type="text/javascript">
    var _yoData = {
        "username": "SAKABE",
        "trigger": "kimatakubot"
      };
  var s = document.createElement("script");
  s.type = "text/javascript";
  s.src = "//yoapp.s3.amazonaws.com/js/yo-button.js";
  (document.head || document.getElementsByTagName("head")[0]).appendChild(s);
</script>
<a class="twitter-timeline" href="https://twitter.com/kimataku_bot"  data-widget-id="446868142568902656" lang="ja">@kimataku_bot からのツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kimatakubot" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <%= favicon_link_tag %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/" data-no-turbolink="1" >Kimatakubot</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li data-no-turbolink="1"><%= link_to "ReleaseNote", "/releases"  %></li>
              <li data-no-turbolink="1"><%= link_to "Paydays", "/paydays"  %></li>
              <li data-no-turbolink="1"><%= link_to "Tweet","/tweets"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= yield %>
        </div>
        <div class="span3">
          <%= render 'layouts/twitter' %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; contact us @kimataku_bot </p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/paydays/_form.html.erb
<%= form_for(@payday) do |f| %>
  <% if @payday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payday.errors.count, "error") %> prohibited this payday from being saved:</h2>

      <ul>
      <% @payday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :twitter_acount_name %><br>
    <%= f.text_area :twitter_acount_name %>
  </div>
  <div class="field">
    <%= f.label :payday %><br>
    <%= f.date_select :payday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paydays/edit.html.erb
<h1>Editing payday</h1>

<%= render 'form' %>

<%= link_to 'Show', @payday %> |
<%= link_to 'Back', paydays_path %>

app/views/paydays/index.html.erb
<h1>Listing paydays</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Payday</th>
    </tr>
  </thead>

  <tbody>
    <% @paydays.each do |payday| %>
      <tr>
        <td><%= payday.title %></td>
        <td><%= payday.payday %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @paydays %>

<br>

<%= link_to 'New Payday', new_payday_path %>

app/views/paydays/new.html.erb
<h1>New payday</h1>

<%= render 'form' %>

<%= link_to 'Back', paydays_path %>

app/views/releases/_form.html.erb
<%= form_for(@release) do |f| %>
  <% if @release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% @release.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :release_at %><br>
    <%= f.date_select :release_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/releases/edit.html.erb
<h1>Editing release</h1>

<%= render 'form' %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<h1>Listing releases</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Release at</th>
    </tr>
  </thead>

  <tbody>
    <% @releases.each do |release| %>
      <tr>
        <td><%= release.title %></td>
        <td><%= release.release_at %></td>
        <td><%= link_to 'Show', release %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Release', new_release_path %>

app/views/releases/new.html.erb
<h1>New release</h1>

<%= render 'form' %>

<%= link_to 'Back', releases_path %>

app/views/releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @release.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= markdown(@release.description) %>
</p>

<p>
  <strong>Release at:</strong>
  <%= @release.release_at %>
</p>

<%= link_to 'Edit', edit_release_path(@release) %> |
<%= link_to 'Back', releases_path %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tweet %><br>
    <%= f.text_area :tweet %>
  </div>
  <div class="field">
    <%= f.label :twitter_acount_name %><br>
    <%= f.text_area :twitter_acount_name %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br>
    <%= f.date_select :started_at %>
  </div>
  <div class="field">
    <%= f.label :ended_at %><br>
    <%= f.date_select :ended_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Tweet</th>
      <th>Twitter acount name</th>
      <th>Started at</th>
      <th>Ended at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.title %></td>
        <td><%= tweet.tweet %></td>
        <td><%= tweet.twitter_acount_name %></td>
        <td><%= tweet.started_at %></td>
        <td><%= tweet.ended_at %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tweet.title %>
</p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<p>
  <strong>Twitter acount name:</strong>
  <%= @tweet.twitter_acount_name %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @tweet.started_at %>
</p>

<p>
  <strong>Ended at:</strong>
  <%= @tweet.ended_at %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>